eureka:
  instance:
    hostname: localhost
server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
       - id: USER-SERVICE
         uri: lb://USER-SERVICE
         predicates:
          - Path=/users/**   
       - id: contact-service
         uri: lb://contact-service
         predicates :
          - Path=/contacts/**
  zipkin:
   enabled: true
   baseUrl: http://localhost:9411/
