server:
  port: 8020
spring:
  cloud:
    gateway:
      routes:
       - id: USER-SERVICE
         uri: lb://USER-SERVICE
         predicates:
          - Path=/users/**   
       - id: contact-service
         uri: lb://contact-service
         predicates :
          - Path=/contacts/**
