eureka:
  instance:
    hostname: localhost
server:
  port: 8022
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: oracle
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sys as sysdba
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dilect: org.hibernate.dialect.Oracle12cDialect
